### ISSUE TITLE
Library creates a file named 'string' with contents 'testtest'

### ISSUE THREAD

**Issue by nfriedly** [jprichardson/string.js#160]
Hey I'm not quite sure what's going here, and it could be due to us using the library incorrectly, but this line https://github.com/jprichardson/string.js/blob/master/lib/string.js#L726 seems to be writing a file named 'string' to the disk with the contents 'test' and then a little later appending another 'test' to it. The stack looks like this:

```
    at String._toEnd (/Users/nfriedly/IonicBluemixDemo/server/node_modules/ibmbluemix/node_modules/shelljs/src/toEnd.js:24:8)
    at String.toEnd (/Users/nfriedly/IonicBluemixDemo/server/node_modules/ibmbluemix/node_modules/shelljs/src/common.js:172:23)
    at getNativeStringProperties (/Users/nfriedly/IonicBluemixDemo/server/node_modules/watson-developer-cloud/node_modules/string/lib/string.js:726:32)
    at Object.<anonymous> (/Users/nfriedly/IonicBluemixDemo/server/node_modules/watson-developer-cloud/node_modules/string/lib/string.js:673:26)
    at Object.<anonymous> (/Users/nfriedly/IonicBluemixDemo/server/node_modules/watson-developer-cloud/node_modules/string/lib/string.js:1103:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

(This was first reported at https://github.com/watson-developer-cloud/nodejs-wrapper/issues/56 )

**Comment by jprichardson** [comment]
Can you paste your `dependencies` and `devDependencies`? Are you using shelljs?

**Comment by nfriedly** [comment]
Here's the dependencies from the app where we're seeing the issue:

```
 "dependencies": {
"express": "4.*",
"body-parser": "*",
"ibmbluemix":"*",
"ibmdata":"*",
"watson-developer-cloud": "*",
"formidable":"*"
},
"devDependencies": {
"grunt": "~0.4.1",
"grunt-simple-mocha": "0.4.0",
"load-grunt-tasks": "~0.3.0",
"time-grunt": "~0.2.9",
"chai": "*",
"mocha": "*",
"when": "*",
"request": "*",
"assert":"*"
},
```

(from https://github.com/cfjedimaster/IonicBluemixDemo/blob/master/server/package.json)

**Comment by nfriedly** [comment]
I *think* that this is the only place where the watson-developer-cloud lib uses `string`: https://github.com/watson-developer-cloud/nodejs-wrapper/blob/cf92e33dc299c646d6710216c89dfec2d698b5b6/lib/requestwrapper.js#L34

**Comment by nfriedly** [comment]
It looks like IconicBluemixDemo uses shelljs in the mobile code, but not in the server code where we're seeing the issue: https://github.com/cfjedimaster/IonicBluemixDemo/blob/cb55991b7b5a66a8e90e3a061f2c9550ba80f27e/mobile/gulpfile.js#L8

**Comment by az7arul** [comment]
I think this there is a known issue, when shelljs is loaded before string.js a file is created because shelljs adds a method `to` in String prototype.

**Comment by jprichardson** [comment]
@az7arul wouldn't a quick fix be if we just detect if the function name is `to` to skip it? It's hacky, but shelljs is the only modern library that I know that tramples over the String prototype.

**Comment by az7arul** [comment]
yeah that will fix it.

**Comment by nfriedly** [comment]
@az7arul Yep, moving `string` as a first-tier dependency and putting a `require('string');` at the top of the file seems to prevent the issue, so I think you're on the right track.

**Comment by nfriedly** [comment]
And @jprichardson yea, a hack in string.js to work around this would be appreciated.

**Comment by az7arul** [comment]
working on it

**Comment by az7arul** [comment]
@jprichardson @nfriedly #161

**Comment by az7arul** [comment]
Fixed in [3.3.1](https://www.npmjs.com/package/string)

**Comment by jprichardson** [comment]
Awesome, thanks @az7arul!
