### ISSUE TITLE
Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by vladfrangu** [jprichardson/string.js#207]
I'm pretty sure I give it a string, but it should be that or something else.. But also, `substr`?
```js
C:\Users\Vlad\Desktop\New folder (2)\node_modules\string\lib\string.js:86
      return new this.constructor(this.s.substr(0, 1).toUpperCase() + this.s.substring(1).toLowerCase());
                                        ^

TypeError: Cannot read property 'substr' of undefined
    at S.capitalize (C:\Users\Vlad\Desktop\New folder (2)\node_modules\string\lib\string.js:86:41)
    at unirest.get.headers.end.res (C:\Users\Vlad\Desktop\New folder (2)\Commands\Public\e621.js:43:43)
    at Request.handleRequestResponse [as _callback] (C:\Users\Vlad\Desktop\New folder (2)\node_modules\unirest\index.js:463:26)
    at Request.self.callback (C:\Users\Vlad\Desktop\New folder (2)\node_modules\unirest\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Vlad\Desktop\New folder (2)\node_modules\unirest\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Vlad\Desktop\New folder (2)\node_modules\unirest\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by vladfrangu** [comment]
I feel slightly dumb, the string was actually null..
